---
- hosts: "{{ hostname }}"
  remote_user: root
  gather_facts: false
  vars:
    packageUrl: "{{ package_url }}"
    downloadPath: /tmp
    deployPath: /data0/www
    deployName: current

  tasks:
    - name: Get war name
      local_action: command basename {{ packageUrl }}
      register: warName

    - name: Stop tomcat
      service: name=tomcat state=stopped

    - name: get build package
      get_url: url={{ packageUrl }} dest=/{{ downloadPath }}/{{ warName.stdout }}

    - name: Unzip war file
      unarchive: src=/{{ downloadPath }}/{{ warName.stdout }} dest={{ deployPath }}/{{ deployName }} copy=no mode=0755 owner=tomcat group=tomcat
      notify: start tomcat    
   
    - name: Delete war file
      file: path={{ downloadPath }}/{{ warName.stdout }} state=absent

  handlers:
    - name: start tomcat
      service: name=tomcat state=started
