---
- name: check instance is already a slave
  mysql_replication:
    mode: getslave
    login_user: root
    login_password: "{{ mysql_password }}"
    login_unix_socket: "{{ socket }}"
  register: status
  failed_when: status.Is_Slave