---
# install a MySQL instance and start it

- hosts: "{{ hosts }}"
  gather_facts: no
  vars:
    mysql_home: /usr/local/mysql
    mysql_conf_home: /etc/mysql
    mysql_data_home: /data0/mysql

  pre_tasks:
    - import_tasks: roles/mysql/tasks/mysql_env_check.yml
    - import_tasks: roles/mysql/tasks/mysql_version.yml

  roles:
    - { role: mysql }
